export const SCHEMA_VERSION = 3;
export const ENGINE_VERSION = '3.0.0-beta.1';
export const RULESET_VERSION = '2026-07-31-phase4-landscapes.1';

export const COMMAND_TYPES = Object.freeze([
  'CHOOSE_TURN_ORDER',
  'DRAW_CARD',
  'SET_CARD',
  'SET_CARD_FROM_DECK',
  'SET_ADAPTIVE_TOKEN',
  'CONSOLIDATE_CARD',
  'MOVE_CARD',
  'FLIP_CARD',
  'ACTIVATE_LANDSCAPE',
  'DISCARD_CARD',
  'MODIFY_FATE',
  'ACTIVATE_EFFECT',
  'ANSWER_PROMPT',
  'DISCARD_TO_HAND_LIMIT',
  'END_TURN',
  'CONCEDE'
]);

export const PROMPT_TYPES = Object.freeze({
  MODAL_CHOICE: 'MODAL_CHOICE',
  CARD_SELECTION: 'CARD_SELECTION',
  BOARD_TARGET: 'BOARD_TARGET',
  BOARD_DESTINATION: 'BOARD_DESTINATION',
  HAND_SELECTION: 'HAND_SELECTION',
  ZONE_SELECTION: 'ZONE_SELECTION',
  REACTION: 'REACTION'
});

export const OPERATION_TYPES = Object.freeze({
  DRAW_CARD: 'DRAW_CARD',
  SET_CARD: 'SET_CARD',
  CONSOLIDATE_CARD: 'CONSOLIDATE_CARD',
  MOVE_CARD: 'MOVE_CARD',
  DISCARD_CARD: 'DISCARD_CARD',
  MODIFY_FATE: 'MODIFY_FATE',
  SET_FATE: 'SET_FATE',
  REVEAL_HAND: 'REVEAL_HAND',
  TRANSFER_CARDS: 'TRANSFER_CARDS',
  CHANGE_CONTROL: 'CHANGE_CONTROL',
  CREATE_MOVEMENT_GRANT: 'CREATE_MOVEMENT_GRANT',
  CREATE_TIMED_PLAYER_STATUS: 'CREATE_TIMED_PLAYER_STATUS',
  CREATE_STATUS: 'CREATE_STATUS',
  REMOVE_STATUS: 'REMOVE_STATUS',
  CREATE_MATCH_STATUS: 'CREATE_MATCH_STATUS',
  REMOVE_MATCH_STATUS: 'REMOVE_MATCH_STATUS',
  TICK_COUNTER_FATE: 'TICK_COUNTER_FATE',
  SET_CARD_COUNTER: 'SET_CARD_COUNTER',
  ADD_SAFE_ROW: 'ADD_SAFE_ROW',
  ADD_SAFE_SQUARE: 'ADD_SAFE_SQUARE',
  CREATE_SQUARE_STATUS: 'CREATE_SQUARE_STATUS',
  DISCARD_AND_GAIN_FATE: 'DISCARD_AND_GAIN_FATE',
  CREATE_CARD_MARK: 'CREATE_CARD_MARK',
  MASS_MODIFY_MATCHING_CARD: 'MASS_MODIFY_MATCHING_CARD',
  RANDOM_DISCARD_HAND: 'RANDOM_DISCARD_HAND',
  RANDOM_STEAL_HAND: 'RANDOM_STEAL_HAND',
  DISCARD_TYPES_AND_GAIN_FATE: 'DISCARD_TYPES_AND_GAIN_FATE',
  SCHEDULE_CARD: 'SCHEDULE_CARD',
  CREATE_TOKENS: 'CREATE_TOKENS',
  CHANGE_PLAYER_COUNTER: 'CHANGE_PLAYER_COUNTER',
  RANDOM_HAND_FATE: 'RANDOM_HAND_FATE',
  CHANGE_ZONE_AFFILIATION: 'CHANGE_ZONE_AFFILIATION',
  RANDOM_TRANSFER_CARDS: 'RANDOM_TRANSFER_CARDS',
  SPLIT_FATE_LOSS_BY_TYPE: 'SPLIT_FATE_LOSS_BY_TYPE',
  CHANGE_LANDSCAPE: 'CHANGE_LANDSCAPE'
});

export const RULE_EVENT_TYPES = Object.freeze({
  CARD_SET: 'CARD_SET',
  CARD_CONSOLIDATED: 'CARD_CONSOLIDATED',
  EFFECT_ACTIVATED: 'EFFECT_ACTIVATED',
  EFFECT_REACTED: 'EFFECT_REACTED',
  CARD_TARGETED: 'CARD_TARGETED',
  CARD_MOVED: 'CARD_MOVED',
  CARD_DISCARDED: 'CARD_DISCARDED',
  CARD_DRAWN: 'CARD_DRAWN',
  DRAW_EFFECT_ACTIVATED: 'DRAW_EFFECT_ACTIVATED',
  CARD_TRANSFERRED: 'CARD_TRANSFERRED',
  CONTROL_CHANGED: 'CONTROL_CHANGED',
  AFFILIATION_CHANGED: 'AFFILIATION_CHANGED',
  AFFILIATION_DECLARED: 'AFFILIATION_DECLARED',
  DECK_SEARCHED: 'DECK_SEARCHED',
  FATE_CHANGED: 'FATE_CHANGED',
  TURN_STARTED: 'TURN_STARTED',
  DRAW_PHASE_COMPLETED: 'DRAW_PHASE_COMPLETED',
  TURN_ENDING: 'TURN_ENDING',
  MATCH_ENDED: 'MATCH_ENDED'
});
