const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),vm=require('node:vm');const root=path.resolve(__dirname,'..');
const sandbox={window:{}};for(const f of ['53-japanese-content.js','53-japanese-catalog.js'])vm.runInNewContext(fs.readFileSync(path.join(root,'src/scripts',f),'utf8'),sandbox);
const map=new Map([...(sandbox.window.FateJapaneseContent||[]),...Object.entries(sandbox.window.FateJapaneseCatalog)].map(([a,b])=>[a.toLowerCase(),b]));
const vars=new Map();
for(const file of fs.readdirSync(path.join(root,'src/styles')).filter(f=>f.endsWith('.css')&&!f.startsWith('localization'))){const p=path.join(root,'src/styles',file),source=fs.readFileSync(p,'utf8');const changed=source.replace(/content\s*:\s*(["'])([^"']*[A-Za-z][^"']*)\1/g,(whole,quote,text)=>{const en=text.replace(/\\A\s*/g,' '),ja=map.get(en.toLowerCase());if(!ja||ja===en)return whole;const id='--fate-label-'+crypto.createHash('sha256').update(en).digest('hex').slice(0,10);vars.set(id,ja);return 'content:var('+id+','+quote+text+quote+')';});if(changed!==source)fs.writeFileSync(p,changed);}
const generated=path.join(root,'src/styles/localization-generated.css');const previous=fs.existsSync(generated)?fs.readFileSync(generated,'utf8'):'';for(const m of previous.matchAll(/(--fate-label-[a-f0-9]+):\s*("(?:\\.|[^"\\])*"|[^;]+);/g))if(!vars.has(m[1]))vars.set(m[1],JSON.parse(m[2]));
fs.writeFileSync(generated,'/* Japanese versions of CSS-generated labels; English remains the CSS fallback. */\nhtml[lang="ja"] {\n'+[...vars].map(([id,ja])=>'  '+id+': '+JSON.stringify(ja)+';').join('\n')+'\n}\n');
const index=path.join(root,'index.html');let html=fs.readFileSync(index,'utf8');if(!html.includes('localization-generated.css'))html=html.replace('<link rel="stylesheet" href="src/styles/localization.css', '<link rel="stylesheet" href="src/styles/localization-generated.css?v=20260929ja2">\n<link rel="stylesheet" href="src/styles/localization.css');fs.writeFileSync(index,html);
console.log('Localized CSS labels: '+vars.size);
