window.FATES_ARCHIVE_DATA = {
  "cards": [
    {
      "id": "01",
      "name": "Felicyta Janowicz",
      "ability": "The White Eagle",
      "type": "Coordinator",
      "aff": "third_great_war",
      "fate": 3,
      "cost": 3,
      "rarity": "square",
      "effect": "All cards you control that are adjacent to this card gains 3 Fate.",
      "flavor": "\"There is no leader in the world, whether of democracies or monarchies, more humble than the Queen of Poland-Lithuania\"",
      "img": "../1.png"
    },
    {
      "id": "02",
      "name": "Anicka Konvicka",
      "ability": "The Starlit Path",
      "type": "Initiator",
      "aff": "eventide",
      "fate": 8,
      "cost": 2,
      "rarity": "star",
      "effect": "Create an extra safe row for yourself in this zone. Any card placed in this zone gains 4 Fate.",
      "flavor": "\"These Seas were not always feared - Once, they were called Pacifique\"",
      "img": "../2.png"
    },
    {
      "id": "03",
      "name": "Howard",
      "ability": "Moffitt Inspiration",
      "type": "Initiator",
      "aff": "reality",
      "fate": 5,
      "cost": 2,
      "rarity": "star",
      "effect": "Select one card in this zone; double its current Fate permanently, then increase its Fate by another 5 permanently.",
      "flavor": "\"The glorious Moffitt King\"",
      "img": "../3.png"
    },
    {
      "id": "04",
      "name": "Zoe",
      "ability": "INTJ Stare",
      "type": "Initiator",
      "aff": "reality",
      "fate": 6,
      "cost": 2,
      "rarity": "triangle",
      "effect": "Select any one square in this card's zone (empty or occupied); your opponent can no longer Consolidate on that square.",
      "flavor": "\"She's definitely Caitlyn's mom\"",
      "img": "../4.png"
    },
    {
      "id": "05",
      "name": "17th British Regiment of Africa",
      "ability": "Liberators of Rwanda",
      "type": "Supporter",
      "aff": "third_great_war",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When set, select one card in this card's zone; it gains 3 Fate permanently.",
      "flavor": "\"The first into Rwanda, and the last out\"",
      "img": "../5.png"
    },
    {
      "id": "06",
      "name": "Jorge Alvarez",
      "ability": "The West Caribbea Trading Company",
      "type": "Initiator",
      "aff": "eventide",
      "fate": 1,
      "cost": 1,
      "rarity": "square",
      "effect": "Search the deck for a card and add it to your hand. You cannot add Star cards.",
      "flavor": "\"In Caribbea, the sun never sets\"",
      "img": "../6.png"
    },
    {
      "id": "07",
      "name": "Maja Kaminska",
      "ability": "Oblique Order",
      "type": "Initiator",
      "aff": "third_great_war",
      "fate": 3,
      "cost": 1,
      "rarity": "star",
      "effect": "This card can also be set from the deck at no cost. This card cannot be set in a contested row. When set, add three supporters from the deck to your hand, and they all gain 4 Fate. For this turn, you can set two extra supporters.",
      "flavor": "\"If Napoleon Bonaparte wore pink ribbons in his hair and listened to My Chemical Romance, he would be Kaminska\"",
      "img": "../7.png"
    },
    {
      "id": "08",
      "name": "Lina",
      "ability": "Autistic Femcel Rizz",
      "type": "Initiator",
      "aff": "reality",
      "fate": 2,
      "cost": 2,
      "rarity": "square",
      "effect": "Search for any \"Reality\" affiliated card from the deck or discard pile and set it with no cost.",
      "flavor": "\"The Ultimate bed-rotter and Denji Cosplayer in one\"",
      "img": "../8.png"
    },
    {
      "id": "09",
      "name": "United Nations 5th Army",
      "ability": "The Battle of Bremen",
      "type": "Supporter",
      "aff": "third_great_war",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "This card counts as 2 Reinforcement",
      "flavor": "\"Led under the command of Maja Kaminska, the 5th Army of the United Nations have won dazzling victories in the European theatre\"",
      "img": "../9.png"
    },
    {
      "id": "10",
      "name": "Post-Modernist Dylan",
      "ability": "Esoteric Annihilation",
      "type": "Coordinator",
      "aff": "expanded_worlds",
      "fate": 3,
      "cost": 2,
      "rarity": "triangle",
      "effect": "While on the field: all of your opponent's cards in this zone lose 2 Fate.",
      "flavor": "\"Destroy. Obliterate. Exterminate. Eradicate. Annihilate. End all\"",
      "img": "../10.png"
    },
    {
      "id": "11",
      "name": "Anne Stone",
      "ability": "Coordination",
      "type": "Coordinator",
      "aff": "eventide",
      "fate": 6,
      "cost": 2,
      "rarity": "triangle",
      "effect": "All Supporters you control in this zone gain 3 Fate.",
      "flavor": "\"A cunning and intelligent diplomat known for her superior efficiency\"",
      "img": "../11.png"
    },
    {
      "id": "12",
      "name": "Makenna",
      "ability": "Robo en la Noche",
      "type": "Coordinator",
      "aff": "expanded_worlds",
      "fate": 4,
      "cost": 1,
      "rarity": "triangle",
      "effect": "Select up to two cards in this card's zone; they are immune to your opponent's effects.",
      "flavor": "\"An ardent protector of Bird-kind\"",
      "img": "../12.png"
    },
    {
      "id": "13",
      "name": "Johnathan Kirby",
      "ability": "The Christmas Day Charter",
      "type": "Initiator",
      "aff": "third_great_war",
      "fate": 2,
      "cost": 1,
      "rarity": "square",
      "effect": "When set: search your deck for up to 2 Supporter cards and add them to your hand.",
      "flavor": "\"As one of Dylan Kirby's fourteen Children, he seems to have inherited his father's persuasiveness\"",
      "img": "../13.png"
    },
    {
      "id": "14",
      "name": "Alondra Hopkins",
      "ability": "Unseen Strikes",
      "type": "Dauntless",
      "aff": "eventide",
      "fate": 14,
      "cost": 4,
      "rarity": "triangle",
      "effect": "While this card is on the field, your opponent cannot set any Supporter adjacent to this card. Any opponent Supporter card that was adjacent or diagonal to this card when it is set are discarded, and this card gains 1 Fate for each one.",
      "flavor": "\"Unmatched speed and agility - her body count is in the thousands\"",
      "img": "../14.png"
    },
    {
      "id": "15",
      "name": "Zsofia Szocs",
      "ability": "Blue Danube Waltz",
      "type": "Coordinator",
      "aff": "third_great_war",
      "fate": 2,
      "cost": 2,
      "rarity": "triangle",
      "effect": "All cards in this zone you control gain 1 Fate for each Coordinator in this zone (max 3 Fate).",
      "flavor": "\"The Beautiful Danube, clear and blue\"",
      "img": "../15.png"
    },
    {
      "id": "16",
      "name": "MINAE Death Squad",
      "ability": "Preserving the Environment",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When set, you can discard an opponent's Supporter in this zone.",
      "flavor": "\"The Ministry of the Environment strives for the reduction of harmful emissions to protect our Sensitive Wildlife - At all costs\"",
      "img": "../16.png"
    },
    {
      "id": "17",
      "name": "Carolyn",
      "ability": "Entropic Chaos",
      "type": "Initiator",
      "aff": "expanded_worlds",
      "fate": 2,
      "cost": 3,
      "rarity": "triangle",
      "effect": "Select any one open square on the field; that square cannot be used for the rest of the game.",
      "flavor": "\"All logic breaks down, and all possibilities become equalized\"",
      "img": "../17.png"
    },
    {
      "id": "18",
      "name": "1st US Marines",
      "ability": "Semper Fidelis",
      "type": "Supporter",
      "aff": "third_great_war",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When set, your opponent's supporters next turn cannot activate their effects. You can only activate this effect three times a game",
      "flavor": "\"The de-facto shock troops of America - Loyal, brave, and true\"",
      "img": "../18.png"
    },
    {
      "id": "19",
      "name": "Květka Svoboda",
      "ability": "The Vltava's Story",
      "type": "Coordinator",
      "aff": "third_great_war",
      "fate": 5,
      "cost": 2,
      "rarity": "triangle",
      "effect": "All Coordinators you control in this zone gain 2 Fate.",
      "flavor": "\"The Queen of Czechoslovakia, once a Street Urchin in Prague\"",
      "img": "../19.png"
    },
    {
      "id": "20",
      "name": "South Wind Spearman",
      "ability": "Shield Wall",
      "type": "Supporter",
      "aff": "eventide",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "This card is immune to all of your opponent's effects.",
      "flavor": "\"In Pacifica, the South Wind Spearmen are the textbook definition of a disciplined and well organized army\"",
      "img": "../20.png"
    },
    {
      "id": "21",
      "name": "Henry Dong",
      "ability": "The Last Revolution",
      "type": "Dauntless",
      "aff": "third_great_war",
      "fate": 10,
      "cost": 3,
      "rarity": "triangle",
      "effect": "While this card is on the field, Select up to two squares adjacent to this card and suppress any of your opponent's coordinator effects on them",
      "flavor": "\"Our workers' revolution, this final revolution to usurp Capitalism's golden throne - will bring the end of history\"",
      "img": "../21.png"
    },
    {
      "id": "22",
      "name": "Isaac Perez",
      "ability": "A Scientist's Inquiry",
      "type": "Initiator",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 1,
      "rarity": "triangle",
      "effect": "Select up to two cards you control in this zone; permanently increase their Fate by 3.",
      "flavor": "\"The Head Scientist of Alpine's experimental method is simple - Always look for another possibility\"",
      "img": "../22.png"
    },
    {
      "id": "23",
      "name": "Cathy",
      "ability": "Cardigan Onslaught",
      "type": "Coordinator",
      "aff": "reality",
      "fate": 3,
      "cost": 2,
      "rarity": "triangle",
      "effect": "All Characters you control in this zone gain 2 Fate.",
      "flavor": "\"Her crippling Cheez-Itz addiction fuels her voracious appetite for Cardigans\"",
      "img": "../23.png"
    },
    {
      "id": "24",
      "name": "Ralph's Courtesy Clerk",
      "ability": "\"Make it Right\"",
      "type": "Supporter",
      "aff": "reality",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "While this card is on the field, Supporters adjacent to this card are worth 1 extra reinforcement.",
      "flavor": "\"An unprecedented master of cart pushing, bagging, and floor sweeps\"",
      "img": "../24.png"
    },
    {
      "id": "25",
      "name": "Zimbabwean Honor Guard",
      "ability": "Africa, United",
      "type": "Supporter",
      "aff": "third_great_war",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When set, you can (at no extra cost) set another copy of this card from the hand or deck (once a turn).",
      "flavor": "\"It is time for Africa to take to the world stage - No more will it be the plaything of foreign powers\"",
      "img": "../25.png"
    },
    {
      "id": "26",
      "name": "UCPD",
      "ability": "A Safer Community",
      "type": "Supporter",
      "aff": "reality",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When set, reveal your opponent's hand.",
      "flavor": "\"Keeping the Students of the University Safe, one tweaker at a time\"",
      "img": "../26.png"
    },
    {
      "id": "27",
      "name": "Kazumi",
      "ability": "Fables of the Old Age",
      "type": "Initiator",
      "aff": "eventide",
      "fate": 1,
      "cost": 1,
      "rarity": "square",
      "effect": "Draw 3 cards.",
      "flavor": "\"An eager bookworm, always willing to raid the local library for any piece of Old Age history she can snag\"",
      "img": "../27.png"
    },
    {
      "id": "28",
      "name": "2nd Polish-Lithuanian Army",
      "ability": "The Army of Exiles",
      "type": "Supporter",
      "aff": "third_great_war",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "This card is able to be set from the deck. This effect only works once a turn, twice a game.",
      "flavor": "\"The entire Polish Army fights from outside their own homeland - and yet they fight no less patriotically\"",
      "img": "../28.png"
    },
    {
      "id": "29",
      "name": "Dylan Kirby",
      "ability": "Leader of the Free World",
      "type": "Initiator",
      "aff": "third_great_war",
      "fate": 3,
      "cost": 1,
      "rarity": "square",
      "effect": "Add up to two \"Third Great War\" cards from the deck or discard pile to your hand.",
      "flavor": "\"Once again, the sleeping giant awakes - The Arsenal of Democracy\"",
      "img": "../29.png"
    },
    {
      "id": "30",
      "name": "Santiago",
      "ability": "El Matador del Mares",
      "type": "Initiator",
      "aff": "eventide",
      "fate": 5,
      "cost": 3,
      "rarity": "triangle",
      "effect": "Select one of your opponent's cards in this zone's contested row; discard it.",
      "flavor": "\"The leader of the Cook Islands has quite a ferocious approach to his diplomacy\"",
      "img": "../30.png"
    },
    {
      "id": "31",
      "name": "Oathbound Noble Fighter",
      "ability": "Hemorrhaging Wound",
      "type": "Supporter",
      "aff": "eventide",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When set, select any card in this card's zone; it loses 3 Fate permanently.",
      "flavor": "\"These mercenaries fight not for money, but for the thrill of battle\"",
      "img": "../31.png"
    },
    {
      "id": "32",
      "name": "Temecula Resident",
      "ability": "Wine Country Fanaticism",
      "type": "Supporter",
      "aff": "reality",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When set, draw 1 card.",
      "flavor": "\"Life of a Temecula resident: Promenade, Old Town, Pechanga Casino, Walmart on Temecula Parkway, repeat\"",
      "img": "../32.png"
    },
    {
      "id": "33",
      "name": "West Caribbea Infantry",
      "ability": "The Company's Finest",
      "type": "Supporter",
      "aff": "eventide",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When set, the next character card that is added to your hand costs 1 less Reinforcement and gains 2 Fate.",
      "flavor": "\"The company's soldiers are above all, highly motivated and highly paid\"",
      "img": "../33.png"
    },
    {
      "id": "34",
      "name": "Rozsi Szocs",
      "ability": "Hungarian Dance",
      "type": "Coordinator",
      "aff": "third_great_war",
      "fate": 3,
      "cost": 2,
      "rarity": "triangle",
      "effect": "Whenever a card would move into this card's zone by any effect, it permanently gains 3 Fate. Setting a card does not count.",
      "flavor": "\"Rozsi's charisma counterparts his sister's administrative abilities. Together, the Twin Monarchs are a capable duo\"",
      "img": "../34.png"
    },
    {
      "id": "35",
      "name": "Alexander the Magnificient",
      "ability": "Hellenic Glory",
      "type": "Dauntless",
      "aff": "third_great_war",
      "fate": "X",
      "cost": 4,
      "rarity": "triangle",
      "effect": "This card's Fate is equal to the combined current Fate value of all Supporters you control in this zone.",
      "flavor": "\"He is the heir to Alexander the Great, not by blood but by blade\"",
      "img": "../35.png"
    },
    {
      "id": "36",
      "name": "Marie L'amboure",
      "ability": "Deterrance",
      "type": "Improvisor",
      "aff": "third_great_war",
      "fate": 6,
      "cost": 2,
      "rarity": "triangle",
      "effect": "Whenever your opponent would Consolidate a card in this zone, reduce the zone's total Fate by 4.",
      "flavor": "\"Another of Dylan Kirby's many offspring - L'amboure is known for the rearmament of the Maginot Line\"",
      "img": "../36.png"
    },
    {
      "id": "37",
      "name": "6th French Fusiliers",
      "ability": "The Anchor of Verdun",
      "type": "Supporter",
      "aff": "third_great_war",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When set, select any Supporter on the field with a \"While this card is on the field\" effect, and copy that effect for this card.",
      "flavor": "\"Thanks to their adaptive defensive doctrine, the 6th French Fusiliers held off the German advance at Verdun for 67 days\"",
      "img": "../37.png"
    },
    {
      "id": "38",
      "name": "Jake",
      "ability": "I'm Fat",
      "type": "Dauntless",
      "aff": "reality",
      "fate": 1,
      "cost": 3,
      "rarity": "triangle",
      "effect": "Once a turn, you can send a Supporter from your hand to the discard to permanently increase this card's Fate by 5.",
      "flavor": "\"Let my body become a totem to Bacchus\"",
      "img": "../38.png"
    },
    {
      "id": "39",
      "name": "Juan Carlos",
      "ability": "Costa Rica's Finest Abs",
      "type": "Initiator",
      "aff": "expanded_worlds",
      "fate": 3,
      "cost": 2,
      "rarity": "square",
      "effect": "Move any of your opponent's cards to any open square in this card's zone.",
      "flavor": "\"A truly divine being - Only he could have toppled Makenna's Fascist Costa Rica\"",
      "img": "../39.png"
    },
    {
      "id": "40",
      "name": "Christopher Erbs",
      "ability": "Hard Times, Strong Men",
      "type": "Improvisor",
      "aff": "expanded_worlds",
      "fate": 6,
      "cost": 2,
      "rarity": "triangle",
      "effect": "At any time during your turn, you can activate this effect; the next card you draw gains 4 Fate (2 uses).",
      "flavor": "\"Leader of an elite mercenary group who patrols the wastes of Temecula, purging it of zombie hordes\"",
      "img": "../40.png"
    },
    {
      "id": "41",
      "name": "Jimmy",
      "ability": "A True Incel's Wrath",
      "type": "Dauntless",
      "aff": "reality",
      "fate": 0,
      "cost": 3,
      "rarity": "triangle",
      "effect": "This card gains 3 Fate for each time you reduced the Fate of your opponent's cards this game (once per card effect use).",
      "flavor": "\"Inside of Jimmy's head, the abyss gazes back\"",
      "img": "../41.png"
    },
    {
      "id": "42",
      "name": "West German Soldier",
      "ability": "For a Free Germany",
      "type": "Supporter",
      "aff": "third_great_war",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When set, draw two cards then discard two cards.",
      "flavor": "\"No more will Germans be passive bystanders - we must avenge history\"",
      "img": "../42.png"
    },
    {
      "id": "43",
      "name": "Mark Kemper",
      "ability": "Elephant Movie 2",
      "type": "Initiator",
      "aff": "reality",
      "fate": 4,
      "cost": 2,
      "rarity": "triangle",
      "effect": "Add a new safe square underneath the safe zone in this card's zone. Later Marks in that zone add to the same row until it is full.",
      "flavor": "\"The lucid mastermind behind Elephant Movie One\"",
      "img": "../43.png"
    },
    {
      "id": "44",
      "name": "Soviet Grenadiers",
      "ability": "The Bears of Russia",
      "type": "Supporter",
      "aff": "third_great_war",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "While this card is adjacent to a Dauntless card, both that card and this card gain 3 Fate.",
      "flavor": "\"Only the strongest and tallest men are worthy of the title, Grenadier\"",
      "img": "../44.png"
    },
    {
      "id": "45",
      "name": "Chingachlook",
      "ability": "The Last Mohican",
      "type": "Dauntless",
      "aff": "eventide",
      "fate": 13,
      "cost": 2,
      "rarity": "triangle",
      "effect": "This is the only character card you can control in this zone. Only one copy of this card can be played.",
      "flavor": "\"Through him, the entire history, legacy, and traditions of the Mohican people will live on. When he dies, so will they\"",
      "img": "../45.png"
    },
    {
      "id": "46",
      "name": "Phil",
      "ability": "The Monarchist Manifesto",
      "type": "Dauntless",
      "aff": "reality",
      "fate": 1,
      "cost": 3,
      "rarity": "square",
      "effect": "For every one of your Draw phases that passes after this card is set, this card permanently gains 2 Fate.",
      "flavor": "\"Let the rot of modernity fail, and reveal the only truth — The Holy Spirit\"",
      "img": "../46.png"
    },
    {
      "id": "47",
      "name": "Great Oak Infantry",
      "ability": "\"We Bleed Red\"",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When this card would be used in the Consolidation of a card, that card gains 3 Fate permanently.",
      "flavor": "\"During a zombie apocalypse, the best thing a high schooler could ask for are some football pads and a pointy piece of metal\"",
      "img": "../47.png"
    },
    {
      "id": "48",
      "name": "Cosmic GF",
      "ability": "The Kitchen at the End of Time",
      "type": "Initiator",
      "aff": "expanded_worlds",
      "fate": 2,
      "cost": 1,
      "rarity": "square",
      "effect": "Add any \"Expanded Worlds\" card from the deck to the hand, then another one from the discard pile to the hand.",
      "flavor": "\"Each egg is a universe - but it seems that even high-omnipotent beings cannot escape the looming specter of gender roles\"",
      "img": "../48.png"
    },
    {
      "id": "49",
      "name": "Irvine Businessman",
      "ability": "The Thousand Year Company",
      "type": "Supporter",
      "aff": "reality",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "While this card is on the field, character cards in this card's zone can be used for consolidation, each worth 1 Reinforcement.",
      "flavor": "\"These soul-less automatons are the lapdogs of the Irvine Company\"",
      "img": "../49.png"
    },
    {
      "id": "50",
      "name": "Berkeley CS Major",
      "ability": "Artillery Distance",
      "type": "Supporter",
      "aff": "reality",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When set, select any zone; on your opponent's next turn, they can no longer set or consolidate cards there, or activate effects.",
      "flavor": "\"Berkeley hoodie? Check. Boba addiction? Check. Anime fan? Check. Bonus section: virgin and leetcode? Check.\"",
      "img": "../50.png"
    },
    {
      "id": "51",
      "name": "Rivera",
      "ability": "Jorge's Right Hand Man",
      "type": "Initiator",
      "aff": "eventide",
      "fate": 3,
      "cost": 2,
      "rarity": "square",
      "effect": "Declare any affiliation; for the next three of your turns, any character you set with that affiliation gains 4 Fate, including characters that would have their affiliation changed to the declared affiliation.",
      "flavor": "\"Everything that Rivera fights for is to ensure his daughter a bright future in West Caribbea\"",
      "img": "../51.png"
    },
    {
      "id": "52",
      "name": "The Vigilantes",
      "ability": "Marked for Death",
      "type": "Supporter",
      "aff": "eventide",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When set, select any Supporter your opponent controls in this zone; make its Reinforcement value 0.",
      "flavor": "\"One with the Sea... One with the Sea...\"",
      "img": "../52.png"
    },
    {
      "id": "53",
      "name": "Colombo Thug",
      "ability": "Thieves and Bullies",
      "type": "Supporter",
      "aff": "eventide",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "While this card is on the field, your opponent's consolidations in this zone cannot use cards from outside zones.",
      "flavor": "\"Everyone in Colombo is poor, but only some are morally bankrupt\"",
      "img": "../53.png"
    },
    {
      "id": "54",
      "name": "Wolf Creek Light Infantry",
      "ability": "Elusive Movements",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When set, you can select one card you control in this zone and move it to any open square in any zone you control, or swap its location with any card you control on the field.",
      "flavor": "\"The motto of the Light Infantry is simple - When in doubt, run away\"",
      "img": "../54.png"
    },
    {
      "id": "55",
      "name": "Bobby Jones",
      "ability": "Cosmic Convergence",
      "type": "Dauntless",
      "aff": "expanded_worlds",
      "fate": 5,
      "cost": 1,
      "rarity": "triangle",
      "effect": "If you control a minimum of 3 cards in this zone and they all have the same affiliation (excluding this card), this card gains 7 Fate.",
      "flavor": "\"A divine being, whose golden hair is said to harbor entire galaxies\"",
      "img": "../55.png"
    },
    {
      "id": "56",
      "name": "Lydia",
      "ability": "Berknomaly!?@#",
      "type": "Improvisor",
      "aff": "expanded_worlds",
      "fate": 7,
      "cost": 2,
      "rarity": "star",
      "effect": "Whenever your opponent would activate the effect of any card, you can negate the effect or suppress it permanently (3 uses).",
      "flavor": "\"How is life with a floating magical sword following me everywhere I go? Not really that bad actually...\"",
      "img": "../56.png"
    },
    {
      "id": "57",
      "name": "Jeremiah Jones",
      "ability": "ALPINE, The Future",
      "type": "Coordinator",
      "aff": "expanded_worlds",
      "fate": 3,
      "cost": 3,
      "rarity": "square",
      "effect": "All Coordinators you control in this zone have their zone auras gain 1 Fate in potency.",
      "flavor": "\"Through Science and technology, ALPINE will become the future hope for all of mankind\"",
      "img": "../57.png"
    },
    {
      "id": "58",
      "name": "Crossroads Worker",
      "ability": "Picking Up the Scraps",
      "type": "Supporter",
      "aff": "reality",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When set, add a Supporter from the discard to your hand.",
      "flavor": "\"Truly, nothing matches the brain numbing agony of DRA...\"",
      "img": "../58.png"
    },
    {
      "id": "59",
      "name": "Czechoslovak \"Maroon Knights\"",
      "ability": "Heraldry of the Lion",
      "type": "Supporter",
      "aff": "third_great_war",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "While this card is on the field, all Supporters you control in this card's zone gain 1 Fate.",
      "flavor": "\"Chivalric knights who protect their country and their honor\"",
      "img": "../59.png"
    },
    {
      "id": "60",
      "name": "IB Student",
      "ability": "College App Frenzy",
      "type": "Supporter",
      "aff": "reality",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When set, search your deck for a Supporter and add it to your hand.",
      "flavor": "\"Maybe the true benefit of IB was the 4000 word essay we wrote along the way\"",
      "img": "../60.png"
    },
    {
      "id": "61",
      "name": "Maria Song",
      "ability": "Precise Shot",
      "type": "Dauntless",
      "aff": "eventide",
      "fate": 9,
      "cost": 3,
      "rarity": "triangle",
      "effect": "When set, select any of your opponent's card on the field. Any other copy of that card in your opponent's hand or deck are discarded.",
      "flavor": "\"That giant cleaver is cool and all but what's the point if I just blow your brains out from over here?\"",
      "img": "../61.png"
    },
    {
      "id": "62",
      "name": "Berkeley Homeless",
      "ability": "People's Park",
      "type": "Supporter",
      "aff": "reality",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When set, you can move this card to any open square in any zone your opponent controls. Neither player can use this card for consolidation. Your opponent can only discard this card by discarding 2 cards from their hand.",
      "flavor": "\"Can you spare a dollar?\"",
      "img": "../62.png"
    },
    {
      "id": "63",
      "name": "Greek Hoplite",
      "ability": "Sons of Macedon",
      "type": "Supporter",
      "aff": "third_great_war",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "This card gains 2 Fate for each copy of this card you control in this zone.",
      "flavor": "\"Ares, in all of his intrepid fervour, is once again realized\"",
      "img": "../63.png"
    },
    {
      "id": "64",
      "name": "Cook Islands Duelist",
      "ability": "Blade Dance",
      "type": "Supporter",
      "aff": "eventide",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "While this card is on the field, one random card your opponent controls adjacent to this card loses 3 Fate, and this card gains 3 Fate.",
      "flavor": "\"Dueling takes a very ostentatious appearance in the Cook Islands, trading practicality for flashiness\"",
      "img": "../64.png"
    },
    {
      "id": "66",
      "name": "Mark Menz",
      "ability": "Beyond Drawings",
      "type": "Initiator",
      "aff": "reality",
      "fate": 4,
      "cost": 2,
      "rarity": "triangle",
      "effect": "Declare an affiliation; change as many cards you control in this zone to that affiliation. This card gains 1 Fate for each card changed this way.",
      "flavor": "\"Steph Curry... MY GOAT!\"",
      "img": "../66.png"
    },
    {
      "id": "67",
      "name": "Mr. Secules",
      "ability": "\"You Just Said Nothing\"",
      "type": "Improvisor",
      "aff": "reality",
      "fate": 4,
      "cost": 1,
      "rarity": "triangle",
      "effect": "Once, when your opponent would activate a character's Initiator effect or a Supporter's when-set effect, negate it.",
      "flavor": "\"Breathe. Relax your shoulders. Unclench your jaw\"",
      "img": "../67.png"
    },
    {
      "id": "68",
      "name": "Great Oak High Schooler",
      "ability": "Home of the Wolfpack",
      "type": "Supporter",
      "aff": "reality",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When set, add any Coordinator from the deck to your hand, excluding Star cards.",
      "flavor": "\"The infamous Jumbotron is a testament to the mediocrity of the school's football program\"",
      "img": "../68.png"
    },
    {
      "id": "69",
      "name": "Breakfast Republic Busser",
      "ability": "Corner! Behind!",
      "type": "Supporter",
      "aff": "reality",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When set, you can select any card you control in this zone; for the next three turns, that card can move once a turn to any zone one zone away.",
      "flavor": "\"May I take/grab/snag/ that Plate for you?\"",
      "img": "../69.png"
    },
    {
      "id": "70",
      "name": "Wine Country Guerilla",
      "ability": "A Gun Behind Every Grapevine",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When this card is discarded in any method, you can move this card to your opponent's hand. It remains in your opponent's hand for 5 turns, where every turn it randomly reduces the Fate of a random card in your opponent's hand at the start of the turn by 2. After 5 effect uses, this card is sent to your discard. While in your opponent's hand, this card is immune to all effects and cannot be set.",
      "flavor": "\"Jorge's Personal Soldiers - Can they hold back the forces of Shenck?\"",
      "img": "../70.png"
    },
    {
      "id": "71",
      "name": "Fort Calvin Watcher",
      "ability": "All Eyes on the I-15",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When set, reveal the next 3 cards your opponent draws during only the Draw Phase. If any are characters, you may send them to the bottom of your opponent's deck.",
      "flavor": "\"These men only have one job - To monitor the flow of traffic on the I-15\"",
      "img": "../71.png"
    },
    {
      "id": "72",
      "name": "Robo en la Noche",
      "ability": "Bane of Birds",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When set, take a card at random from your opponent's hand and add it to your hand. When that card is discarded, it returns to your opponent's deck.",
      "flavor": "\"Who is the mysterious thief in the shadows? The Robo en la Noche?\"",
      "img": "../72.png"
    },
    {
      "id": "73",
      "name": "ALPINE Expeditionary",
      "ability": "Global Missions",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When set, discard all Initiators and Improvisors you control in this zone. This card gains Fate equal to the total Fate of cards discarded, and once a turn this card can move to an open square on your side of the field.",
      "flavor": "\"Superior technology and equipment allows for these individuals to be dropped anywhere on earth and easily survive for years\"",
      "img": "../73.png"
    },
    {
      "id": "74",
      "name": "Selva Islands Pirate",
      "ability": "A New Pacifica",
      "type": "Supporter",
      "aff": "eventide",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When you draw or add this card in any way to your hand, you can set one extra Supporter for this turn only.",
      "flavor": "\"Serving under the infamous Richard Fleur, these men are the sworn rivals of the Cook Islands Confederation\"",
      "img": "../74.png"
    },
    {
      "id": "77",
      "name": "Duncan Heyward",
      "ability": "A Hundred Lives of Men",
      "type": "Coordinator",
      "aff": "eventide",
      "fate": 6,
      "cost": 3,
      "rarity": "square",
      "effect": "When set, declare any affiliation. While this card is on the field, any card you control in this zone with that declared affiliation gains 4 Fate.",
      "flavor": "\"Among all men in Pacifica, Heyward is the most respected, feared, and influential. And yet, it seems a tired shadow clings to him...\"",
      "img": "../77.png"
    },
    {
      "id": "78",
      "name": "Chaparral Hoplite",
      "ability": "Scrappy Ambushers",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "The next time you would consolidate a card in this zone, you can set the card face down in the zone. At any time during your turn, you can flip the card face up.",
      "flavor": "\"Despite being surrounded and cut off from the rest of Temecula by Zombie hordes, these kids will still fight with heart\"",
      "img": "../78.png"
    },
    {
      "id": "79",
      "name": "Havano Citizen",
      "ability": "A True Freedom",
      "type": "Supporter",
      "aff": "eventide",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "Whenever your opponent would target you or one of your cards with an effect, while this card is in your hand; negate that effect or suppress it, then set this card from your hand at no cost.",
      "flavor": "\"The citizens of Havano are known for their distinctive use of colorful ribbons - it is a symbol for their cherished freedom\"",
      "img": "../79.png"
    },
    {
      "id": "80",
      "name": "Apparition of Berkeley",
      "ability": "Political Ramblings",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When set, you can discard any Character card you control in this zone to draw 2 cards.",
      "flavor": "\"You'd think that wrathful apparitions would be a cause for concern, but all they do is ramble about neo-liberalism\"",
      "img": "../80.png"
    },
    {
      "id": "65",
      "name": "1st West Caribbea Marines",
      "ability": "Sea-Men",
      "type": "Supporter",
      "aff": "eventide",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "This card can only be set in contested rows. When set, this card increases its own Fate to 4.",
      "flavor": "\"Hand picked from the veterans of the Caribbea Revolution, these men are capable of braving any tempest\"",
      "img": "../65.png"
    },
    {
      "id": "75",
      "name": "The Ledger-keepers",
      "ability": "The Silent Watchers",
      "type": "Supporter",
      "aff": "eventide",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When set, you can copy the effect of any Supporter on the field with a when set effect and immediately activate it.",
      "flavor": "\"Everyone who has ever lived and died in Pacifica - Has an archival record kept and maintained by the Ledger Keepers\"",
      "img": "../75.png"
    },
    {
      "id": "76",
      "name": "ALPINE Infantry",
      "ability": "Infiltration",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "effect": "When set, this card gains 4 Fate. However this card cannot count for any bonuses, is immune to all effects and cannot be used for Consolidation.",
      "flavor": "\"A mere company of these futuristic soldiers could overthrow a small country\"",
      "img": "../76.png"
    }
  ],
  "lore": []
};
