window.FATES_ARCHIVE_DATA = {
  "generatedAt": "2026-07-24T06:35:15.138Z",
  "cardCount": 109,
  "cards": [
    {
      "id": "01",
      "name": "Felicyta Janowicz",
      "ability": "The White Eagle",
      "type": "Coordinator",
      "aff": "third_great_war",
      "fate": 6,
      "cost": 3,
      "rarity": "square",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "All cards you control that are adjacent to this card gains 4 Fate.",
      "flavor": "\"There is no leader in the world, whether of democracies or monarchies, more humble than the Queen of Poland-Lithuania\"",
      "img": "../1.png"
    },
    {
      "id": "02",
      "name": "Anicka Konvicka",
      "ability": "The Starlit Path",
      "type": "Initiator",
      "aff": "eventide",
      "fate": 8,
      "cost": 2,
      "rarity": "star",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Create an extra safe row for yourself in this zone. Any card placed in this zone gains 4 Fate.",
      "flavor": "\"These Seas were not always feared - Once, they were called Pacifique\"",
      "img": "../2.png"
    },
    {
      "id": "03",
      "name": "Howard",
      "ability": "Moffitt Inspiration",
      "type": "Initiator",
      "aff": "reality",
      "fate": 5,
      "cost": 2,
      "rarity": "star",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Select one card in this zone; double its current Fate permanently, then increase its Fate by another 5 permanently.",
      "flavor": "\"The glorious Moffitt King\"",
      "img": "../3.png"
    },
    {
      "id": "04",
      "name": "Zoe",
      "ability": "INTJ Stare",
      "type": "Initiator",
      "aff": "reality",
      "fate": 6,
      "cost": 2,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Select one square in this card's zone; your opponent can no longer Consolidate on or from that square.",
      "flavor": "\"She's definitely Caitlyn's mom\"",
      "img": "../4.png"
    },
    {
      "id": "05",
      "name": "17th British Regiment of Africa",
      "ability": "Liberators of Rwanda",
      "type": "Supporter",
      "aff": "third_great_war",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, select one card in this card's zone; it gains 3 Fate permanently.",
      "flavor": "\"The first into Rwanda, and the last out\"",
      "img": "../5.png"
    },
    {
      "id": "06",
      "name": "Jorge Alvarez",
      "ability": "The West Caribbea Trading Company",
      "type": "Initiator",
      "aff": "eventide",
      "fate": 1,
      "cost": 1,
      "rarity": "square",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Search the deck for a card and add it to your hand. You cannot add Star cards.",
      "flavor": "\"In Caribbea, the sun never sets\"",
      "img": "../6.png"
    },
    {
      "id": "07",
      "name": "Maja Kaminska",
      "ability": "Oblique Order",
      "type": "Initiator",
      "aff": "third_great_war",
      "fate": 3,
      "cost": 1,
      "rarity": "star",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "This card can also be set from the deck at no cost. This card cannot be set in a contested row. When set, add three supporters from the deck to your hand, and they all gain 4 Fate. For this turn, you can set two extra supporters.",
      "flavor": "\"If Napoleon Bonaparte wore pink ribbons in his hair and listened to My Chemical Romance, he would be Kaminska\"",
      "img": "../7.png"
    },
    {
      "id": "08",
      "name": "Lina",
      "ability": "Autistic Femcel Rizz",
      "type": "Initiator",
      "aff": "reality",
      "fate": 2,
      "cost": 2,
      "rarity": "square",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Search for any \"Reality\" affiliated card from the deck or discard pile and set it with no cost.",
      "flavor": "\"The Ultimate bed-rotter and Denji Cosplayer in one\"",
      "img": "../8.png"
    },
    {
      "id": "09",
      "name": "United Nations 5th Army",
      "ability": "The Battle of Bremen",
      "type": "Supporter",
      "aff": "third_great_war",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "This card counts as 2 Reinforcement",
      "flavor": "\"Led under the command of Maja Kaminska, the 5th Army of the United Nations have won dazzling victories in the European theatre\"",
      "img": "../9.png"
    },
    {
      "id": "10",
      "name": "Post-Modernist Dylan",
      "ability": "Esoteric Annihilation",
      "type": "Coordinator",
      "aff": "expanded_worlds",
      "fate": 5,
      "cost": 2,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "While on the field: all of your opponent's cards in this zone lose 3 Fate.",
      "flavor": "\"Destroy. Obliterate. Exterminate. Eradicate. Annihilate. End all\"",
      "img": "../10.png"
    },
    {
      "id": "11",
      "name": "Anne Stone",
      "ability": "Coordination",
      "type": "Coordinator",
      "aff": "eventide",
      "fate": 6,
      "cost": 2,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "All Supporters you control in this zone gain 3 Fate.",
      "flavor": "\"A cunning and intelligent diplomat known for her superior efficiency\"",
      "img": "../11.png"
    },
    {
      "id": "12",
      "name": "Makenna",
      "ability": "Robo en la Noche",
      "type": "Coordinator",
      "aff": "expanded_worlds",
      "fate": 4,
      "cost": 1,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Select up to two cards in this card's zone; they are immune to your opponent's effects.",
      "flavor": "\"An ardent protector of Bird-kind\"",
      "img": "../12.png"
    },
    {
      "id": "13",
      "name": "Johnathan Kirby",
      "ability": "The Christmas Day Charter",
      "type": "Initiator",
      "aff": "third_great_war",
      "fate": 2,
      "cost": 1,
      "rarity": "square",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set: search your deck for up to 2 Supporter cards and add them to your hand.",
      "flavor": "\"As one of Dylan Kirby's fourteen Children, he seems to have inherited his father's persuasiveness\"",
      "img": "../13.png"
    },
    {
      "id": "14",
      "name": "Alondra Hopkins",
      "ability": "Unseen Strikes",
      "type": "Dauntless",
      "aff": "eventide",
      "fate": 14,
      "cost": 4,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "While this card is on the field, your opponent cannot set any Supporter adjacent to this card. Any opponent Supporter card that was adjacent or diagonal to this card when it is set are discarded, and this card gains 1 Fate for each one.",
      "flavor": "\"Unmatched speed and agility - her body count is in the thousands\"",
      "img": "../14.png"
    },
    {
      "id": "15",
      "name": "Zsofia Szocs",
      "ability": "Blue Danube Waltz",
      "type": "Coordinator",
      "aff": "third_great_war",
      "fate": 5,
      "cost": 2,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Each time you would set a Coordinator in this zone, all cards you control in this zone gain 1 Fate.",
      "flavor": "\"The Beautiful Danube, clear and blue\"",
      "img": "../15.png"
    },
    {
      "id": "16",
      "name": "MINAE Death Squad",
      "ability": "Preserving the Environment",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, you can discard an opponent's Supporter in this zone.",
      "flavor": "\"The Ministry of the Environment strives for the reduction of harmful emissions to protect our Sensitive Wildlife - At all costs\"",
      "img": "../16.png"
    },
    {
      "id": "17",
      "name": "Carolyn",
      "ability": "Entropic Chaos",
      "type": "Initiator",
      "aff": "expanded_worlds",
      "fate": 2,
      "cost": 3,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Select any one open square on the field; that square cannot be used for the rest of the game.",
      "flavor": "\"All logic breaks down, and all possibilities become equalized\"",
      "img": "../17.png"
    },
    {
      "id": "18",
      "name": "1st US Marines",
      "ability": "Semper Fidelis",
      "type": "Supporter",
      "aff": "third_great_war",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, your opponent's supporters next turn cannot activate their effects. You can only activate this effect three times a game",
      "flavor": "\"The de-facto shock troops of America - Loyal, brave, and true\"",
      "img": "../18.png"
    },
    {
      "id": "19",
      "name": "Květka Svoboda",
      "ability": "The Vltava's Story",
      "type": "Coordinator",
      "aff": "third_great_war",
      "fate": 4,
      "cost": 2,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "All Coordinators you control in this card's zone gains 3 Fate.",
      "flavor": "\"The Queen of Czechoslovakia, once a Street Urchin in Prague\"",
      "img": "../19.png"
    },
    {
      "id": "20",
      "name": "South Wind Spearman",
      "ability": "Shield Wall",
      "type": "Supporter",
      "aff": "eventide",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "This card is immune to all of your opponent's effects.",
      "flavor": "\"In Pacifica, the South Wind Spearmen are the textbook definition of a disciplined and well organized army\"",
      "img": "../20.png"
    },
    {
      "id": "21",
      "name": "Henry Dong",
      "ability": "The Last Revolution",
      "type": "Dauntless",
      "aff": "third_great_war",
      "fate": 10,
      "cost": 3,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "While this card is on the field, Select up to two squares adjacent to this card and suppress any of your opponent's Coordinator effects on them",
      "flavor": "\"Our workers' revolution, this final revolution to usurp Capitalism's golden throne - will bring the end of history\"",
      "img": "../21.png"
    },
    {
      "id": "22",
      "name": "Isaac Perez",
      "ability": "A Scientist's Inquiry",
      "type": "Initiator",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 1,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Select up to two cards you control in this zone; permanently increase their Fate by 3.",
      "flavor": "\"The Head Scientist of Alpine's experimental method is simple - Always look for another possibility\"",
      "img": "../22.png"
    },
    {
      "id": "23",
      "name": "Cathy",
      "ability": "Cardigan Onslaught",
      "type": "Coordinator",
      "aff": "reality",
      "fate": 3,
      "cost": 2,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "All Characters you control in this zone gain 2 Fate.",
      "flavor": "\"Her crippling Cheez-Itz addiction fuels her voracious appetite for Cardigans\"",
      "img": "../23.png"
    },
    {
      "id": "24",
      "name": "Ralph's Courtesy Clerk",
      "ability": "\"Make it Right\"",
      "type": "Supporter",
      "aff": "reality",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "While this card is on the field, Supporters adjacent to this card are worth 1 extra reinforcement.",
      "flavor": "\"An unprecedented master of cart pushing, bagging, and floor sweeps\"",
      "img": "../24.png"
    },
    {
      "id": "25",
      "name": "Zimbabwean Honor Guard",
      "ability": "Africa, United",
      "type": "Supporter",
      "aff": "third_great_war",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "While this card is on the field, any card adjacent to another card of the same affiliation you control gains 1 Fate (max 1 Fate).",
      "flavor": "\"It is time for Africa to take to the world stage - No more will it be the plaything of foreign powers\"",
      "img": "../assets/morale-card-reworks/25.png?v=20260829a"
    },
    {
      "id": "26",
      "name": "UCPD",
      "ability": "A Safer Community",
      "type": "Supporter",
      "aff": "reality",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Activate Effect: Reveal your opponent's hand.",
      "flavor": "\"Keeping the Students of the University Safe, one tweaker at a time\"",
      "img": "../26.png"
    },
    {
      "id": "27",
      "name": "Kazumi",
      "ability": "Fables of the Old Age",
      "type": "Initiator",
      "aff": "eventide",
      "fate": 1,
      "cost": 1,
      "rarity": "square",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Draw 3 cards.",
      "flavor": "\"An eager bookworm, always willing to raid the local library for any piece of Old Age history she can snag\"",
      "img": "../27.png"
    },
    {
      "id": "28",
      "name": "2nd Polish-Lithuanian Army",
      "ability": "The Army of Exiles",
      "type": "Supporter",
      "aff": "third_great_war",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Once per turn, this card can be set from the deck without counting towards the Supporter set limit for that turn.",
      "flavor": "\"The entire Polish Army fights from outside their own homeland - and yet they fight no less patriotically\"",
      "img": "../28.png"
    },
    {
      "id": "29",
      "name": "Dylan Kirby",
      "ability": "Leader of the Free World",
      "type": "Initiator",
      "aff": "third_great_war",
      "fate": 3,
      "cost": 1,
      "rarity": "square",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Add up to two \"Third Great War\" cards from the deck or discard pile to your hand.",
      "flavor": "\"Once again, the sleeping giant awakes - The Arsenal of Democracy\"",
      "img": "../29.png"
    },
    {
      "id": "30",
      "name": "Santiago",
      "ability": "El Matador del Mares",
      "type": "Initiator",
      "aff": "eventide",
      "fate": 5,
      "cost": 3,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Select one of your opponent's cards in this zone's contested row; discard it.",
      "flavor": "\"The leader of the Cook Islands has quite a ferocious approach to his diplomacy\"",
      "img": "../30.png"
    },
    {
      "id": "31",
      "name": "Oathbound Noble Fighter",
      "ability": "Hemorrhaging Wound",
      "type": "Supporter",
      "aff": "eventide",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, select any card in this card's zone; it loses 3 Fate permanently.",
      "flavor": "\"These mercenaries fight not for money, but for the thrill of battle\"",
      "img": "../31.png"
    },
    {
      "id": "32",
      "name": "Temecula Resident",
      "ability": "Wine Country Fanaticism",
      "type": "Supporter",
      "aff": "reality",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, draw 1 card.",
      "flavor": "\"Life of a Temecula resident: Promenade, Old Town, Pechanga Casino, Walmart on Temecula Parkway, repeat\"",
      "img": "../32.png"
    },
    {
      "id": "33",
      "name": "West Caribbea Infantry",
      "ability": "The Company's Finest",
      "type": "Supporter",
      "aff": "eventide",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, the next character card that is added to your hand costs 1 less Reinforcement and gains 2 Fate.",
      "flavor": "\"The company's soldiers are above all, highly motivated and highly paid\"",
      "img": "../33.png"
    },
    {
      "id": "34",
      "name": "Rozsi Szocs",
      "ability": "Hungarian Dance",
      "type": "Coordinator",
      "aff": "third_great_war",
      "fate": 3,
      "cost": 2,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Whenever a card would move into this card's zone by any effect, it permanently gains 3 Fate. Setting a card does not count.",
      "flavor": "\"Rozsi's charisma counterparts his sister's administrative abilities. Together, the Twin Monarchs are a capable duo\"",
      "img": "../34.png"
    },
    {
      "id": "35",
      "name": "Alexander the Magnificient",
      "ability": "Hellenic Glory",
      "type": "Dauntless",
      "aff": "third_great_war",
      "fate": 12,
      "cost": 3,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Every Morale Calculation, half of this card's total Fate is inflicted as Morale Damage.",
      "flavor": "\"He is the heir to Alexander the Great, not by blood but by blade\"",
      "img": "../35.png?v=20260828a"
    },
    {
      "id": "36",
      "name": "Marie L'amboure",
      "ability": "Deterrance",
      "type": "Improvisor",
      "aff": "third_great_war",
      "fate": 6,
      "cost": 2,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Whenever your opponent would Consolidate a card in this zone, reduce the zone's total Fate by 4.",
      "flavor": "\"Another of Dylan Kirby's many offspring - L'amboure is known for the rearmament of the Maginot Line\"",
      "img": "../36.png"
    },
    {
      "id": "37",
      "name": "6th French Fusiliers",
      "ability": "The Anchor of Verdun",
      "type": "Supporter",
      "aff": "third_great_war",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, select any Supporter on the field with a \"While this card is on the field\" effect, and copy that effect for this card.",
      "flavor": "\"Thanks to their adaptive defensive doctrine, the 6th French Fusiliers held off the German advance at Verdun for 67 days\"",
      "img": "../37.png"
    },
    {
      "id": "38",
      "name": "Jake",
      "ability": "I'm Fat",
      "type": "Dauntless",
      "aff": "reality",
      "fate": 1,
      "cost": 3,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Once a turn, you can send a Supporter from your field to the discard to permanently increase this card's Fate by 4.",
      "flavor": "\"Let my body become a totem to Bacchus\"",
      "img": "../38.png"
    },
    {
      "id": "39",
      "name": "Juan Carlos",
      "ability": "Costa Rica's Finest Abs",
      "type": "Initiator",
      "aff": "expanded_worlds",
      "fate": 3,
      "cost": 2,
      "rarity": "square",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Move any of your opponent's cards to any open square in this card's zone.",
      "flavor": "\"A truly divine being - Only he could have toppled Makenna's Fascist Costa Rica\"",
      "img": "../39.png"
    },
    {
      "id": "40",
      "name": "Christopher Erbs",
      "ability": "Hard Times, Strong Men",
      "type": "Improvisor",
      "aff": "expanded_worlds",
      "fate": 6,
      "cost": 2,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "At any time during your turn, you can activate this effect; the next card you draw gains 4 Fate (2 uses).",
      "flavor": "\"Leader of an elite mercenary group who patrols the wastes of Temecula, purging it of zombie hordes\"",
      "img": "../40.png"
    },
    {
      "id": "41",
      "name": "Jimmy",
      "ability": "A True Incel's Wrath",
      "type": "Dauntless",
      "aff": "reality",
      "fate": 0,
      "cost": 3,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "This card gains 3 Fate for each time you reduced the Fate of your opponent's cards this game (once per card effect use).",
      "flavor": "\"Inside of Jimmy's head, the abyss gazes back\"",
      "img": "../41.png"
    },
    {
      "id": "42",
      "name": "West German Soldier",
      "ability": "For a Free Germany",
      "type": "Supporter",
      "aff": "third_great_war",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, draw two cards then discard two cards.",
      "flavor": "\"No more will Germans be passive bystanders - we must avenge history\"",
      "img": "../42.png"
    },
    {
      "id": "43",
      "name": "Mark Kemper",
      "ability": "Elephant Movie 2",
      "type": "Initiator",
      "aff": "reality",
      "fate": 4,
      "cost": 2,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Add a new safe square underneath the safe zone in this card's zone. Later Marks in that zone add to the same row until it is full.",
      "flavor": "\"The lucid mastermind behind Elephant Movie One\"",
      "img": "../43.png"
    },
    {
      "id": "44",
      "name": "Soviet Grenadiers",
      "ability": "The Bears of Russia",
      "type": "Supporter",
      "aff": "third_great_war",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "While this card is on the field, declare a card type. If this card is adjacent to a card of that type, this card and one random matching adjacent card gain 3 Fate (max 1 target).",
      "flavor": "\"Only the strongest and tallest men are worthy of the title, Grenadier\"",
      "img": "../44.png?v=20260828a"
    },
    {
      "id": "45",
      "name": "Chingachlook",
      "ability": "The Last Mohican",
      "type": "Dauntless",
      "aff": "eventide",
      "fate": 13,
      "cost": 2,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "This is the only character card you can control in this zone. Only one copy of this card can be played.",
      "flavor": "\"Through him, the entire history, legacy, and traditions of the Mohican people will live on. When he dies, so will they\"",
      "img": "../45.png"
    },
    {
      "id": "46",
      "name": "Phil",
      "ability": "The Monarchist Manifesto",
      "type": "Dauntless",
      "aff": "reality",
      "fate": 1,
      "cost": 3,
      "rarity": "square",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "For every one of your Draw phases that passes after this card is set, this card permanently gains 2 Fate.",
      "flavor": "\"Let the rot of modernity fail, and reveal the only truth — The Holy Spirit\"",
      "img": "../46.png"
    },
    {
      "id": "47",
      "name": "Great Oak Infantry",
      "ability": "\"We Bleed Red\"",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When this card would be used in the Consolidation of a card, that card gains 3 Fate permanently.",
      "flavor": "\"During a zombie apocalypse, the best thing a high schooler could ask for are some football pads and a pointy piece of metal\"",
      "img": "../47.png"
    },
    {
      "id": "48",
      "name": "Cosmic GF",
      "ability": "The Kitchen at the End of Time",
      "type": "Initiator",
      "aff": "expanded_worlds",
      "fate": 3,
      "cost": 1,
      "rarity": "square",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Add any \"Expanded Worlds\" card from the deck to the hand, then add one non-Star \"Expanded Worlds\" card from the discard pile to the hand.",
      "flavor": "\"Each egg is a universe - but it seems that even high-omnipotent beings cannot escape the looming specter of gender roles\"",
      "img": "../48.png"
    },
    {
      "id": "49",
      "name": "Irvine Businessman",
      "ability": "The Thousand Year Company",
      "type": "Supporter",
      "aff": "reality",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "While this card is on the field, character cards in this card's zone can be used for consolidation, each worth 1 Reinforcement.",
      "flavor": "\"These soul-less automatons are the lapdogs of the Irvine Company\"",
      "img": "../49.png"
    },
    {
      "id": "50",
      "name": "Berkeley CS Major",
      "ability": "Artillery Distance",
      "type": "Supporter",
      "aff": "reality",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, select any zone; on your opponent's next turn, they can no longer set or consolidate cards there, or activate effects.",
      "flavor": "\"Berkeley hoodie? Check. Boba addiction? Check. Anime fan? Check. Bonus section: virgin and leetcode? Check.\"",
      "img": "../50.png"
    },
    {
      "id": "51",
      "name": "Rivera",
      "ability": "Jorge's Right Hand Man",
      "type": "Initiator",
      "aff": "eventide",
      "fate": 3,
      "cost": 2,
      "rarity": "square",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Declare any affiliation; for the next three of your turns, any character you set with that affiliation gains 4 Fate, including characters that would have their affiliation changed to the declared affiliation.",
      "flavor": "\"Everything that Rivera fights for is to ensure his daughter a bright future in West Caribbea\"",
      "img": "../51.png"
    },
    {
      "id": "52",
      "name": "The Vigilantes",
      "ability": "Marked for Death",
      "type": "Supporter",
      "aff": "eventide",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, select one card your opponent controls in this zone. When it leaves the field, discard one random card from your opponent's hand.",
      "flavor": "\"One with the Sea... One with the Sea...\"",
      "img": "../52.png"
    },
    {
      "id": "53",
      "name": "Colombo Thug",
      "ability": "Thieves and Bullies",
      "type": "Supporter",
      "aff": "eventide",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "While this card is on the field, your opponent's consolidations in this zone cannot use cards from outside zones.",
      "flavor": "\"Everyone in Colombo is poor, but only some are morally bankrupt\"",
      "img": "../53.png"
    },
    {
      "id": "54",
      "name": "Wolf Creek Light Infantry",
      "ability": "Elusive Movements",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, you can select one card you control in this zone and move it to any open square on your side of the field, or swap its location with any card you control on the field.",
      "flavor": "\"The motto of the Light Infantry is simple - When in doubt, run away\"",
      "img": "../54.png"
    },
    {
      "id": "55",
      "name": "Bobby Jones",
      "ability": "Cosmic Convergence",
      "type": "Dauntless",
      "aff": "expanded_worlds",
      "fate": 5,
      "cost": 1,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "If you control a minimum of 3 cards in this zone and they all have the same affiliation (excluding this card), this card gains 5 Fate.",
      "flavor": "\"A divine being, whose golden hair is said to harbor entire galaxies\"",
      "img": "../55.png"
    },
    {
      "id": "56",
      "name": "Lydia",
      "ability": "Berknomaly!?@#",
      "type": "Improvisor",
      "aff": "expanded_worlds",
      "fate": 7,
      "cost": 2,
      "rarity": "star",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Whenever your opponent would activate the effect of any card, you can negate the effect or suppress it permanently (3 uses).",
      "flavor": "\"How is life with a floating magical sword following me everywhere I go? Not really that bad actually...\"",
      "img": "../56.png"
    },
    {
      "id": "57",
      "name": "Jeremiah Jones",
      "ability": "ALPINE, The Future",
      "type": "Coordinator",
      "aff": "expanded_worlds",
      "fate": 3,
      "cost": 3,
      "rarity": "square",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "All Coordinators you control in this zone have their zone auras gain 1 Fate in potency.",
      "flavor": "\"Through Science and technology, ALPINE will become the future hope for all of mankind\"",
      "img": "../57.png"
    },
    {
      "id": "58",
      "name": "Crossroads Worker",
      "ability": "Picking Up the Scraps",
      "type": "Supporter",
      "aff": "reality",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, add a Supporter from the discard to your hand.",
      "flavor": "\"Truly, nothing matches the brain numbing agony of DRA...\"",
      "img": "../58.png"
    },
    {
      "id": "59",
      "name": "Czechoslovak \"Maroon Knights\"",
      "ability": "Heraldry of the Lion",
      "type": "Supporter",
      "aff": "third_great_war",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "While this card is on the field, all Supporters you control in this card's zone gain 1 Fate.",
      "flavor": "\"Chivalric knights who protect their country and their honor\"",
      "img": "../59.png"
    },
    {
      "id": "60",
      "name": "IB Student",
      "ability": "College App Frenzy",
      "type": "Supporter",
      "aff": "reality",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, search your deck for a Supporter and add it to your hand.",
      "flavor": "\"Maybe the true benefit of IB was the 4000 word essay we wrote along the way\"",
      "img": "../60.png"
    },
    {
      "id": "61",
      "name": "Maria Song",
      "ability": "Precise Shot",
      "type": "Dauntless",
      "aff": "eventide",
      "fate": 9,
      "cost": 3,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, reveal all Character cards in your opponent's hand and select one. All copies of that card in their hand, deck, and on the field lose 7 Fate.",
      "flavor": "\"That giant cleaver is cool and all but what's the point if I just blow your brains out from over here?\"",
      "img": "../61.png"
    },
    {
      "id": "62",
      "name": "Berkeley Homeless",
      "ability": "People's Park",
      "type": "Supporter",
      "aff": "reality",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, you can move this card to any open square in any zone your opponent controls. Neither player can use this card for consolidation. Your opponent can only discard this card by discarding 2 cards from their hand.",
      "flavor": "\"Can you spare a dollar?\"",
      "img": "../62.png"
    },
    {
      "id": "63",
      "name": "Greek Hoplite",
      "ability": "Sons of Macedon",
      "type": "Supporter",
      "aff": "third_great_war",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "This card gains 2 Fate for each copy of this card you control in this zone.",
      "flavor": "\"Ares, in all of his intrepid fervour, is once again realized\"",
      "img": "../63.png"
    },
    {
      "id": "64",
      "name": "Cook Islands Duelist",
      "ability": "Blade Dance",
      "type": "Supporter",
      "aff": "eventide",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "While this card is on the field, one random card your opponent controls adjacent to this card loses 3 Fate, and this card gains 3 Fate.",
      "flavor": "\"Dueling takes a very ostentatious appearance in the Cook Islands, trading practicality for flashiness\"",
      "img": "../64.png"
    },
    {
      "id": "66",
      "name": "Mark Menz",
      "ability": "Beyond Drawings",
      "type": "Initiator",
      "aff": "reality",
      "fate": 3,
      "cost": 1,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Declare an affiliation; change as many cards you control in this zone to that affiliation. This card gains 1 Fate for each card changed this way.",
      "flavor": "\"Steph Curry... MY GOAT!\"",
      "img": "../66.png"
    },
    {
      "id": "67",
      "name": "Mr. Secules",
      "ability": "\"You Just Said Nothing\"",
      "type": "Improvisor",
      "aff": "reality",
      "fate": 4,
      "cost": 1,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Once, when your opponent would activate a character's Initiator effect or a Supporter's when-set effect, negate it.",
      "flavor": "\"Breathe. Relax your shoulders. Unclench your jaw\"",
      "img": "../67.png"
    },
    {
      "id": "68",
      "name": "Great Oak High Schooler",
      "ability": "Home of the Wolfpack",
      "type": "Supporter",
      "aff": "reality",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, add any Coordinator from the deck to your hand, excluding Star cards.",
      "flavor": "\"The infamous Jumbotron is a testament to the mediocrity of the school's football program\"",
      "img": "../68.png"
    },
    {
      "id": "69",
      "name": "Breakfast Republic Busser",
      "ability": "Corner! Behind!",
      "type": "Supporter",
      "aff": "reality",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, you can select any card you control in this zone; for the next three turns, that card can move once a turn to any zone one zone away.",
      "flavor": "\"May I take/grab/snag/ that Plate for you?\"",
      "img": "../69.png"
    },
    {
      "id": "70",
      "name": "Wine Country Guerilla",
      "ability": "A Gun Behind Every Grapevine",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When this card is discarded in any method, you can move this card to your opponent's hand. It remains in your opponent's hand for 5 turns, where every turn it randomly reduces the Fate of a random card in your opponent's hand at the start of the turn by 2. After 5 effect uses, this card is sent to your discard. While in your opponent's hand, this card is immune to all effects and cannot be set.",
      "flavor": "\"Jorge's Personal Soldiers - Can they hold back the forces of Shenck?\"",
      "img": "../70.png"
    },
    {
      "id": "71",
      "name": "Fort Calvin Watcher",
      "ability": "All Eyes on the I-15",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, reveal the next 3 cards your opponent draws during only the Draw Phase. On the next revealed Character, send it to the bottom of the deck. This effect expires after the third eligible draw.",
      "flavor": "\"These men only have one job - To monitor the flow of traffic on the I-15\"",
      "img": "../71.png"
    },
    {
      "id": "72",
      "name": "Robo en la Noche",
      "ability": "Bane of Birds",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, take a card at random from your opponent's hand and add it to your hand. After that card is set, when it leaves the field, it returns to its original owner's discard.",
      "flavor": "\"Who is the mysterious thief in the shadows? The Robo en la Noche?\"",
      "img": "../72.png"
    },
    {
      "id": "73",
      "name": "ALPINE Expeditionary",
      "ability": "Global Missions",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, discard all Initiators and Improvisors you control in this zone. This card gains Fate equal to the total Fate of cards discarded, and once a turn this card can move to an open square on your side of the field.",
      "flavor": "\"Superior technology and equipment allows for these individuals to be dropped anywhere on earth and easily survive for years\"",
      "img": "../73.png"
    },
    {
      "id": "74",
      "name": "Selva Islands Pirate",
      "ability": "A New Pacifica",
      "type": "Supporter",
      "aff": "eventide",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When you draw or add this card in any way to your hand, you can set one extra Supporter for this turn only.",
      "flavor": "\"Serving under the infamous Richard Fleur, these men are the sworn rivals of the Cook Islands Confederation\"",
      "img": "../74.png"
    },
    {
      "id": "77",
      "name": "Duncan Heyward",
      "ability": "A Hundred Lives of Men",
      "type": "Coordinator",
      "aff": "eventide",
      "fate": 6,
      "cost": 3,
      "rarity": "square",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, declare any affiliation. While this card is on the field, any card you control in this zone with that declared affiliation gains 4 Fate.",
      "flavor": "\"Among all men in Pacifica, Heyward is the most respected, feared, and influential. And yet, it seems a tired shadow clings to him...\"",
      "img": "../77.png"
    },
    {
      "id": "78",
      "name": "Chaparral Hoplite",
      "ability": "Scrappy Ambushers",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "The next time you would consolidate a card in this zone, you can set the card face down in the zone. At any time during your turn, you can flip the card face up.",
      "flavor": "\"Despite being surrounded and cut off from the rest of Temecula by Zombie hordes, these kids will still fight with heart\"",
      "img": "../78.png"
    },
    {
      "id": "79",
      "name": "Havano Citizen",
      "ability": "A True Freedom",
      "type": "Supporter",
      "aff": "eventide",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Whenever your opponent would target you or one of your cards with an effect, while this card is in your hand; negate that effect or suppress it, then set this card from your hand at no cost.",
      "flavor": "\"The citizens of Havano are known for their distinctive use of colorful ribbons - it is a symbol for their cherished freedom\"",
      "img": "../79.png"
    },
    {
      "id": "80",
      "name": "Apparition of Berkeley",
      "ability": "Political Ramblings",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, you can discard any Character card you control in this zone to draw 2 cards.",
      "flavor": "\"You'd think that wrathful apparitions would be a cause for concern, but all they do is ramble about neo-liberalism\"",
      "img": "../80.png"
    },
    {
      "id": "81",
      "name": "Wojciech",
      "ability": "Pierogi Barrage",
      "type": "Initiator",
      "aff": "expanded_worlds",
      "fate": 4,
      "cost": 2,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "For each card your opponent set or consolidated last turn, add a Pierogi Counter to your hand. Pierogi Counters stay in your hand for 1 turn, are immune to all effects, and cannot be discarded by your opponent. They can be placed in contested squares or any square your opponent owns, including added squares, and stay there for 3 of their turns.",
      "flavor": "\"Wojciech's advanced age has given him ample time to refine his pierogi craft - He is a true artist!\"",
      "img": "../81.png"
    },
    {
      "id": "82",
      "name": "Felicyta Janowicz (Youth)",
      "ability": "A Quaint Polish Village",
      "type": "Initiator",
      "aff": "expanded_worlds",
      "fate": 4,
      "cost": 3,
      "rarity": "square",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Change the landscape to any of your choice.",
      "flavor": "\"Snow-capped peaks, picturesque rivers, and pine trees as far as the horizon...\"",
      "img": "../82.png"
    },
    {
      "id": "83",
      "name": "Sebastyen Janowicz",
      "ability": "Visegrad",
      "type": "Initiator",
      "aff": "expanded_worlds",
      "fate": 3,
      "cost": 2,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "All Character cards you control in this zone gain 2 Fate permanently.",
      "flavor": "\"Sebastyen's vision was to see an autonomous Eastern Europe, one that didn't have to bow to foreign powers like the European Union\"",
      "img": "../83.png"
    },
    {
      "id": "84",
      "name": "Květka Svoboda",
      "ability": "Flower Picking",
      "type": "Dauntless",
      "aff": "expanded_worlds",
      "fate": 8,
      "cost": 3,
      "rarity": "square",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, add any Expanded Worlds Character card from the deck to the hand and set it at no cost, excluding copies of this card.",
      "flavor": "\"Felicytaaa! Look outside, its snowing, its snowing! Hurry up and wake up we have to go play with everyone!\"",
      "img": "../84.png"
    },
    {
      "id": "85",
      "name": "Felicyta Janowicz (Specters)",
      "ability": "A Specter's Lament",
      "type": "Dauntless",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 4,
      "rarity": "square",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "This card gains 1 Fate for the total amount of times your opponent set a Supporter this game.",
      "flavor": "\"A blood-stained axe, a shattered bayonet, a burning flag - I saw the last thing they saw in the fleeting moments of their lives\"",
      "img": "../85.png"
    },
    {
      "id": "86",
      "name": "Boleslaw Kopewicz",
      "ability": "A Bombastic Character",
      "type": "Improvisor",
      "aff": "expanded_worlds",
      "fate": 4,
      "cost": 2,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Whenever your opponent searches for a card, draw 1 card, and this card gains 2 Fate.",
      "flavor": "\"Boleslaw is the de-facto uncle of the Janowicz family - controversial and disruptive, but charismatic and amusing\"",
      "img": "../86.png"
    },
    {
      "id": "87",
      "name": "Květka Svoboda (Ukulele)",
      "ability": "A Noble Effort at a Ballad",
      "type": "Initiator",
      "aff": "expanded_worlds",
      "fate": 3,
      "cost": 2,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Starting now, when you would consolidate a card, it gains 3 Fate, and this bonus continues until you set a Supporter.",
      "flavor": "\"Let me sing you a song! It goes like... em... ughhh... something... wow!\"",
      "img": "../87.png"
    },
    {
      "id": "88",
      "name": "Rozsi Szocs (Youth)",
      "ability": "Terrible Twins: Toy Sword",
      "type": "Dauntless",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 3,
      "rarity": "square",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "This card gains 2 Fate for each Character card you control on the field.",
      "flavor": "\"This sword is a priceless antique from the late Matthias I of Hungary... with it, all of the Danube is mine!\"",
      "img": "../88.png"
    },
    {
      "id": "89",
      "name": "Zsofia Szocs (Youth)",
      "ability": "Terrible Twins: Diva",
      "type": "Dauntless",
      "aff": "expanded_worlds",
      "fate": 7,
      "cost": 2,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "As long as you activate less than 10 Supporter effects this game, this card gains 7 Fate.",
      "flavor": "\"Ummm can you tell Rozsi to read somewhere else in the house? His aura is giving me bad skin...\"",
      "img": "../89.png"
    },
    {
      "id": "90",
      "name": "Wojciech (Fisherman)",
      "ability": "Catch of the Day",
      "type": "Initiator",
      "aff": "expanded_worlds",
      "fate": 3,
      "cost": 1,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "Declare any affiliation. Two random cards with that affiliation are added to your hand from the deck, and they both gain 3 Fate.",
      "flavor": "\"Wojciech, a retired Army General, now but a simple fisherman who enjoys the gentle trickling of humble mountain streams\"",
      "img": "../90.png"
    },
    {
      "id": "91",
      "name": "Wodny Potok Villager",
      "ability": "A Snowy Village",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "For the next five turns, your opponent cannot change the current landscape. You can only activate this effect twice a game",
      "flavor": "\"Life in Wodny Potok is straight out of a children's Christmas novel\"",
      "img": "../91.png"
    },
    {
      "id": "92",
      "name": "Wodny Potok Lumberjack",
      "ability": "Wood for the Hearth",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "While this card is on the field, any Supporter you set in this zone has their effect negated or suppressed, but gains 1 Reinforcement",
      "flavor": "\"In the cold of the Polish winter, there is no home without a roaring hearth\"",
      "img": "../92.png"
    },
    {
      "id": "93",
      "name": "Wodny Potok Youth",
      "ability": "Snowball Fight",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "While this card is on the field, you can select any card your opponent controls in this Zone and reduce its Fate by 1, Once a turn",
      "flavor": "\"The Wodny Potok youth spend their time throwing snowballs and pestering their parents to take them to the city\"",
      "img": "../93.png"
    },
    {
      "id": "94",
      "name": "Wodny Potok Mailman",
      "ability": "Mail Delivery",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, select any Triangle card in your deck. That card will be added to your hand in four turns",
      "flavor": "\"Through frigid blizzards and overly inquisitive seniors, your mail will be delivered!\"",
      "img": "../94.png"
    },
    {
      "id": "95",
      "name": "Carpathian Specter",
      "ability": "Thousand Year Sorrow",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "This card gains 1 Fate for every two turns it is on the field, maximum of six times.",
      "flavor": "\"The shadows of those who fell in forgotten battles, condemned to an eternity of lamentation\"",
      "img": "../95.png"
    },
    {
      "id": "96",
      "name": "Wodny Potok Snow Shoveler",
      "ability": "Shovel",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, return four random cards in your discard pile to your deck, excluding Star cards.",
      "flavor": "\"Maybe the real Christmas miracle is how Sebastyen is able to convince a group of grown adults to shovel snow for minimum wage\"",
      "img": "../96.png"
    },
    {
      "id": "97",
      "name": "Visegrad Politician",
      "ability": "Administrative Bloat",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, your opponent's next two consolidations cost 1 more Reinforcement.",
      "flavor": "\"Every week, these fat men in suits come to have dinner parties with dad - they are all so boring!!!\"",
      "img": "../97.png"
    },
    {
      "id": "98",
      "name": "Wodny Potok Skier",
      "ability": "Avalanche Escape",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "This card will always appear in your opening hand as an additional card.",
      "flavor": "\"Pine trees are the leading cause of fatal accidents in Wodny Potok\"",
      "img": "../98.png"
    },
    {
      "id": "99",
      "name": "Rozsi and Zsofia (Youth)",
      "ability": "The Blame Game",
      "type": "Initiator",
      "aff": "expanded_worlds",
      "fate": 4,
      "cost": 1,
      "rarity": "triangle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "For the next five turns, your Supporters are classified as Characters. If you control any Rozsi or Zsofia card, this card has no cost. This card uses Characters for its consolidation.",
      "flavor": "",
      "img": "../99.png"
    },
    {
      "id": "100",
      "name": "Felicyta and Květka (Youth)",
      "ability": "Wintertide",
      "type": "Dauntless",
      "aff": "expanded_worlds",
      "fate": 12,
      "cost": 3,
      "rarity": "square",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "This card gains 2 Fate for each of your turns that the \"Snow on the Carpathians\" landscape is active. If you control any Felicyta or Květka card, this card gains 3 Fate. This card uses Characters for its consolidation.",
      "flavor": "",
      "img": "../100.png"
    },
    {
      "id": "65",
      "name": "1st West Caribbea Marines",
      "ability": "Sea-Men",
      "type": "Supporter",
      "aff": "eventide",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "This card can only be set in contested rows. When set, this card increases its own Fate to 4.",
      "flavor": "\"Hand picked from the veterans of the Caribbea Revolution, these men are capable of braving any tempest\"",
      "img": "../65.png"
    },
    {
      "id": "75",
      "name": "The Ledger-keepers",
      "ability": "The Silent Watchers",
      "type": "Supporter",
      "aff": "eventide",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, you can copy the effect of any Supporter on the field with a when set effect and immediately activate it.",
      "flavor": "\"Everyone who has ever lived and died in Pacifica - Has an archival record kept and maintained by the Ledger Keepers\"",
      "img": "../75.png"
    },
    {
      "id": "76",
      "name": "ALPINE Infantry",
      "ability": "Infiltration",
      "type": "Supporter",
      "aff": "expanded_worlds",
      "fate": 1,
      "cost": 0,
      "rarity": "circle",
      "set": "core",
      "token": false,
      "retired": false,
      "effect": "When set, this card gains 4 Fate. However this card cannot count for any bonuses, is immune to all effects and cannot be used for Consolidation.",
      "flavor": "\"A mere company of these futuristic soldiers could overthrow a small country\"",
      "img": "../76.png"
    },
    {
      "id": "bh01",
      "name": "Anička Konvička (Voyager)",
      "ability": "Brave Horizons",
      "type": "Dauntless",
      "aff": "eventide",
      "fate": 12,
      "cost": 3,
      "rarity": "star",
      "set": "brave_horizons",
      "token": false,
      "retired": false,
      "effect": "Once a turn, you can move this card to any open square in any zone. If you do so, draw 1 card. This card is immune to all effects.",
      "flavor": "\"Infinity beckons, but I already see all Ends\"",
      "img": "../bh1.png"
    },
    {
      "id": "bh02",
      "name": "Joie",
      "ability": "Thousand Reel Stare",
      "type": "Coordinator",
      "aff": "reality",
      "fate": 1,
      "cost": 5,
      "rarity": "square",
      "set": "brave_horizons",
      "token": false,
      "retired": false,
      "effect": "Each time you activate a draw effect, all cards you control in this card's zone gain 1 Fate.",
      "flavor": "\"You're so fake\"",
      "img": "../bh2.png"
    },
    {
      "id": "bh03",
      "name": "Ali, The Indomitable",
      "ability": "He, Who is Unyielding",
      "type": "Improvisor",
      "aff": "expanded_worlds",
      "fate": 2,
      "cost": 3,
      "rarity": "triangle",
      "set": "brave_horizons",
      "token": false,
      "retired": false,
      "effect": "When this card appears in your hand, it transfers to your opponent's hand, where it is immune to all effects. While in your opponent's hand, this card prevents your opponent's hand from exceeding 6 cards. This card loses its immunity when set.",
      "flavor": "\"A completely normal man, impervious to all manner of weaponry\"",
      "img": "../bh3.png"
    },
    {
      "id": "bh04",
      "name": "Anicka Konvicka (Selva Island)",
      "ability": "The Destruction of Paradise",
      "type": "Initiator",
      "aff": "eventide",
      "fate": 6,
      "cost": 4,
      "rarity": "triangle",
      "set": "brave_horizons",
      "token": false,
      "retired": false,
      "effect": "Declare a Card type-all cards your opponent controls in this zone of that card type losses 20 Fate split evenly, permanently",
      "flavor": "\"Everything I do...its all to find Kazumi and bring her home\"",
      "img": "../bh4.png"
    },
    {
      "id": "bh05",
      "name": "Taylor",
      "ability": "The Art of Mimicry",
      "type": "Initiator",
      "aff": "expanded_worlds",
      "fate": 5,
      "cost": 1,
      "rarity": "star",
      "set": "brave_horizons",
      "token": false,
      "retired": false,
      "effect": "When this card is added to your hand by being searched or drawn, a second copy of it appears. When set, this card copies the effect of any card in your hand or deck",
      "flavor": "\"Empathetic and brave, a master of disguises-Taylor is one of ALPINE's most valuable operatives\"",
      "img": "../bh5.png"
    },
    {
      "id": "bh06",
      "name": "Achille Laurent",
      "ability": "Adaptive Tactics",
      "type": "Initiator",
      "aff": "third_great_war",
      "fate": 2,
      "cost": 1,
      "rarity": "triangle",
      "set": "brave_horizons",
      "token": false,
      "retired": false,
      "effect": "This effect cannot be activated until turn 6. When set, add 3 \"Adaptive Tactics\" tokens to your hand. These tokens have no set limit and 2 Fate each. When they are set, they can become any card type, placement type, affiliation, and rarity",
      "flavor": "\"The Swallow of France is known for his ability to adapt to any battlefield\"",
      "img": "../bh6.png"
    },
    {
      "id": "bh07",
      "name": "Agent-K",
      "ability": "Overclock",
      "type": "Coordinator",
      "aff": "expanded_worlds",
      "fate": 3,
      "cost": 3,
      "rarity": "square",
      "set": "brave_horizons",
      "token": false,
      "retired": false,
      "effect": "For each Dauntless card this card is adjacent to, all cards you control in this zone gain 2 Fate.",
      "flavor": "\"A prodigious talent in hacking and code breaking\"",
      "img": "../bh7.png"
    },
    {
      "id": "bh08",
      "name": "Maja Kaminska (University)",
      "ability": "Mischievous Activities",
      "type": "Coordinator",
      "aff": "expanded_worlds",
      "fate": 4,
      "cost": 3,
      "rarity": "square",
      "set": "brave_horizons",
      "token": false,
      "retired": false,
      "effect": "Each time you would negate or suppress an effect, all cards you control in this zone gain 2 Fate.",
      "flavor": "\"We shall draw silly faces on the Palace of Science and Culture\"",
      "img": "../bh8.png"
    },
    {
      "id": "bh25",
      "name": "Jimmy (Viltrumite)",
      "ability": "Left Hook of the Incel",
      "type": "Dauntless",
      "aff": "reality",
      "fate": 8,
      "cost": 3,
      "rarity": "square",
      "set": "brave_horizons",
      "token": false,
      "retired": true,
      "effect": "When set, discard any card on the field.",
      "flavor": "\"I will burn this planet down before I spend another minute among these foids\"",
      "img": "../blank.png"
    }
  ],
  "lore": []
};
